### ISSUE TITLE
[Suggestion] Peer chosen movie weeks

### ISSUE THREAD

**Issue by hcoffey1** [chrisdean258/movies#4]
I believe interspersing peer chosen films into the list would be a fun addition. Each person would have one week where they could share a movie of their choice with the group.

**Comment by chrisdean258** [comment]
To accommodate movie suggestions, we will alternate watching 2 movies from the list with 1 movie from the list and 1 suggested movie. The person who suggests the movie will be randomly determined. The first movie shall be suggested August 31, 2022 and discussed September 14.

Also some movies that simply make sense to watch paired with other movies (such Terminator with Terminator 2) can be inserted without a person "choosing" that film.
